<?php

namespace App\Form;

use Symfony\Component\Form\FormBuilderInterface;

class GameEditType extends GameType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('WinnerID');
    }

}